### PR TITLE
Fix(?) for hitsplats displaying above other interfaces

### PR DESCRIPTION
**Pull request by YeahImRose**
Hello!
A small fix for hitsplats displaying over the other interfaces.
There's a chance I missed something in testing, so please double check if you can.

Thanks!

PS: might look into that other issue of splats staying on dead enemies too

### CODE REVIEW

**Comment by YeahImRose** [comment]
@Ferrariic Are you no longer maintaining this? If not I'm willing to clean up and get it fully working on the current update, but I'd need you to do PRs and such.

If you just want this off your hands I'd be willing to maintain it, too.

**Comment by Ferrariic** [comment]
> @Ferrariic Are you no longer maintaining this? If not I'm willing to clean up and get it fully working on the current update, but I'd need you to do PRs and such.
> 
> If you just want this off your hands I'd be willing to maintain it, too. 

That's fine I'll submit a PR

**Comment by Ferrariic** [comment]
> @Ferrariic Are you no longer maintaining this? If not I'm willing to clean up and get it fully working on the current update, but I'd need you to do PRs and such.
> 
> If you just want this off your hands I'd be willing to maintain it, too. 

What is your discord?

**Comment by YeahImRose** [comment]
> > @Ferrariic Are you no longer maintaining this? If not I'm willing to clean up and get it fully working on the current update, but I'd need you to do PRs and such.
> > 
> > If you just want this off your hands I'd be willing to maintain it, too. 
> 
> What is your discord?, I'll be happy to give you ownership of the project. 

rose.zip

**Pull request merged**
